import type { Metadata } from "next";
import { Rubik } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Nav from "./components/nav";

const rubik = Rubik({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={rubik.className}>
        <Nav></Nav>
        {children}
      </body>
    </html>
  );
}
